name: airflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab
  - matplotlib
  - mysqlclient
  - numpy
  - pandas
  - scipy
  - seaborn
  - pymongo
  - plotly

