name: airflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter==1.0.0
  - jupyterlab
  - matplotlib
  - mysqlclient==1.3.14
  - numpy==1.16.3
  - pandas==1.0
  - scipy==1.2.1
  - seaborn==0.9.0
  - pymongo==3.9.0

